### ISSUE TITLE
Sandy's requested site changes

### ISSUE THREAD

**Issue by Crista2019** [dhmit/dhmit-site#16]
- [x] On the page that shows my photo and the title of rereading project, the title should read "**The** Reading Redux: Calculating the Values of Rereading"

- [x] Change the description so that it reads as follows:

> If we can simulate the experience of rereading a specific text, what useful information can we gather about how readers rethink, clarify, and nuance their thoughts about or their interpretations of that text? Associate Professor of Literature, Sandy Alexandre, and the DH Lab will collaborate on this project to investigate these and other questions around close reading and rereading texts, using computational tools to gather and analyze the data.

**Comment by Crista2019** [comment]
Changes made in `rereading_changes_branched_from_tobacco_working_navbar_and_modal`.
I tried to make it clear in the branch title, but I branched `rereading_project_description_change` from master at first, where the navbar and modals don't work. Because of this, I rebranched and worked from the `tobacco_network_changes` branch instead

**Comment by ryaanahmed** [comment]
@Crista2019 -- just FYI the problem with the navbar and modals is that the production version of the JS and CSS hadn't been built after some changes were made. They'll work in dev mode, since that's just hotloading code to a dev server, but in order to get them to work in the plain static page, you'll have to run the default gulp task (just by running `gulp` with no flags) at the command line.

**Comment by ryaanahmed** [comment]
@Crista2019 -- Did you make a PR for this work?
